# Generated by Django 4.1.3 on 2023-01-04 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0003_alter_autor_apellido_alter_autor_correo_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articulos',
            new_name='Articulo',
        ),
    ]
