# Generated by Django 4.1.3 on 2023-01-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0004_rename_articulos_articulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreadorBlog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=80, verbose_name='Apellido')),
                ('edad', models.IntegerField(blank=True, null=True, verbose_name='Edad')),
                ('correo', models.EmailField(max_length=100, unique=True, verbose_name='Correo')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='usuario')),
            ],
        ),
        migrations.AlterModelOptions(
            name='articulo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='autor',
            options={},
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='autor_id',
        ),
        migrations.AddField(
            model_name='articulo',
            name='autor',
            field=models.CharField(max_length=200, null=True, verbose_name='autor'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='cuerpo',
            field=models.TextField(null=True, verbose_name='cuerpo'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='AppBlog/imagenes'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=200, verbose_name='subtitulo'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='fecha_publicacion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, verbose_name='titulo'),
        ),
    ]
