# Generated by Django 4.1.3 on 2023-01-15 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0005_creadorblog_usuario_alter_articulo_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='fecha_publicacion',
            new_name='fecha_entrega',
        ),
    ]
