# Generated by Django 4.1.3 on 2023-01-16 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0006_rename_fecha_publicacion_articulo_fecha_entrega'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='fecha_entrega',
        ),
    ]
