# Generated by Django 4.1.3 on 2023-01-22 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppBlog', '0007_remove_articulo_fecha_entrega'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creadorblog',
            old_name='apellido',
            new_name='apellidocreador',
        ),
        migrations.RenameField(
            model_name='creadorblog',
            old_name='correo',
            new_name='correocreador',
        ),
        migrations.RenameField(
            model_name='creadorblog',
            old_name='descripcion',
            new_name='descripcioncreador',
        ),
        migrations.RenameField(
            model_name='creadorblog',
            old_name='edad',
            new_name='edadcreador',
        ),
        migrations.RenameField(
            model_name='creadorblog',
            old_name='nombre',
            new_name='nombrecreador',
        ),
        migrations.AddField(
            model_name='articulo',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='avatars')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
