# Generated by Django 4.1.3 on 2023-01-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0008_rename_apellido_creadorblog_apellidocreador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha_entrega'),
        ),
    ]
